@startuml

title Use Case Diagram

left to right direction

actor Продавець
rectangle "Програма" {
    usecase (Запакувати необхідну кількість пристроїв)
    usecase (Отримати кількість пристроїв)
    
    Продавець -- (Запакувати необхідну кількість пристроїв)
    Продавець -- (Отримати кількість пристроїв)
    (Отримати кількість пристроїв) <. (Запакувати необхідну кількість пристроїв) : include
}

@enduml
