@startuml

hide circle
title UML-діаграма концептуальних класів

class User {
  login: string
  password: string
  name: string
}

class Consumer {
  order: Order
}

class Seller {
}

User "*" <|-- "*" Consumer
User "*" --|> "*" Seller
Seller "1" --> "*" Consumer : "Can see the order"

@enduml
