@startuml

title UML-діаграма активності

start

:Споживач обирає опцію "Стрворити замовлення";

repeat:
  :Споживач обирає товар;
  :Споживач додає товар до корзини;
  
  if (Чи є хоча б 1 товар у корзині?) then (Так)
    :Зберегти дані про товари;
    :Запитати місце доставки;
    :Запитати про оплату;
    if (Оплата пройшла успішно) then (Так)
      :Вивести повідомлення про успішну операцію;
    else (Ні)
      :Вивести повідомлення про помилку;
    endif
  else (Ні)
    :Вивести повідомлення, що немає жодного товару у корзині;
  endif
  

@enduml
